name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: main/projects/VS2022/raylib-game-template.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Main depot
      uses: actions/checkout@v3
      with:
        path: main
    
    - name: Checkout raylib side by side
      uses: actions/checkout@v3
      with:
        repository: raysan5/raylib
        path: raylib

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        pushd main/projects/VS2022
        msbuild.exe raylib-game-template.sln /target:raylib /property:Configuration=Release /property:Platform=x64
        msbuild.exe raylib-game-template.sln /target:raylib /property:Configuration=Release.DLL /property:Platform=x64
        popd
